name: cargo-deny

on:
  push:
    branches:
      - '**'
    paths:
      - '**/Cargo.toml'
      - 'deny.toml'
      - '.github/workflows/deny.yml'
  pull_request:
    branches:
      - main
      - 'release/**'
    paths:
      - '**/Cargo.toml'
      - 'deny.toml'
      - '.github/workflows/deny.yml'
  schedule:
    - cron: '0 6 * * *'

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check advisories bans licenses sources
